// <auto-generated />
using System;
using GalaTour.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GalaTour.Migrations
{
    [DbContext(typeof(ExcursionContext))]
    [Migration("20191007134648_CreateNew")]
    partial class CreateNew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GalaTour.Models.Excursion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("DocLink");

                    b.Property<string>("Duration");

                    b.Property<string>("HotelLink");

                    b.Property<string>("HotelName");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<string>("ThePriceInclude");

                    b.HasKey("ID");

                    b.ToTable("Excursions");
                });
#pragma warning restore 612, 618
        }
    }
}
